config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      post 'likes'
    end
  end  

   root 'posts#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :likes
    has_many :users, through: :likes
    
    include SimpleRecommender::Recommendable
    similar_by :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :likes   
  has_many :posts , through: :likes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy,:likes]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json

  
  def create
   
    obj = S3_BUCKET.objects[params[:file].original_filename]
    
    # Upload the file
    obj.write(
      file: params[:file],
      acl: :public_read
    )
    
    # Create an object for the upload
    @post = Post.new(
			url: obj.public_url,
			name: obj.key,
			title: params[:title]
		)
    
    # Save the upload
    if @post.save
      redirect_to posts_path, success: 'File successfully uploaded'
    else
      flash.now[:notice] = 'There was an error'
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def likes
      Like.where(post_id: @post.id , user_id: current_user.id).first_or_create
      

      redirect_to(@post)
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    
      
    
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title,:url,:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_alert.html.erb
<div>
  <% flash.each do |name,msg| %>
    <%= content_tag :div , msg , class: "alert alert-info" %>
  <% end %>  
</div> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
      <%= link_to "Recommendation App" , root_path , class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home" , root_path %></li>
        <li><%= link_to "Create New Post" , new_post_path %></li>
        
      </ul>
      
     

      

      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
           
            <li><%= link_to edit_user_registration_path do  %>
                <i class="glyphicon glyphicon-user"></i> Account Settings
                <% end %>
            </li>
            <li><%= link_to destroy_user_session_path , method: :delete , data: {confirm: "Wanna Log out ?"} do  %>
                <i class="glyphicon glyphicon-log-out"></i> Sign Out
                <% end %>
            </li>
            
            
        <% else %>
            <li><%= link_to new_user_registration_path do  %>
                <i class="glyphicon glyphicon-user"></i> Sign Up
                <% end %>
            </li>
            <li><%= link_to user_session_path do %>
                <i class="glyphicon glyphicon-log-in"> LogIn</i>
                <% end %>
            </li>
        
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Likes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= render 'layouts/alert' %>

<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<h1>Upload a file</h1>

<%= form_tag posts_path, enctype: 'multipart/form-data' do %>
  <%= text_field_tag :title %>
	<%= file_field_tag :file  %>
	<%= submit_tag 'Upload file' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<h1 class="center">Listing Posts</h1>

<br></br>

  
    
    <% @posts.each do |post| %>
    <div class="center">
    <div class="row">
    <div class="col-md-12">
      
        <div class="panel panel-default">
          <div class="panel-body">
           
           <h4><strong><%= link_to post.title , post %></strong></h4>
        
            <p><%= pluralize(post.likes.count, "vote") %></p>
            <p><%= button_to 'Like', likes_post_path(post), method: :post %></p>
            <p><%= link_to 'Show', post %> |
            <%= link_to 'Edit', edit_post_path(post) %> |
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
           
          </div>
        </div>
        
      
    </div>  
    </div>
    </div>
    <% end %>
  



</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<div class="row">
	<div class="col-md-6">	
		
		<%= image_tag @post.url,  :size => '260x180' %>
		<p><%= link_to @post.name, @post.url %></p>
	</div>
		
</div>
<div class="row">
	<div class="col-md-12">
		<ul>
		<% @post.similar_items.each do |post| %>
			<li><%= post.title %></li>
		<% end %>
		</ul>
	</div>
</div>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>